## code to prepare `paysdf` dataset goes here
paysdf <- data.frame("France"=c("Ajoute un photo de profile",
                                "Ecrit ton nom",
                                "Ecrit ton prenom",
                                "Ecrit ton adresse complet",
                                "Ecrit ton adresse mail",
                                "Ecrit le code du pays telephonique",
                                "Ecrit ton numero telephonique",
                                "",
                                "NOM",
                                "Prenom",
                                "123 Rue Charmant, 38000 Grenoble France",
                                "Peregrin.Touque@Shire.com",
                                "+33",
                                "0784941207",
                                "Erreur, votre numero doit etre 10 chiffres en longeur",
                                "Erreur, vous devez utiliser que les chiffres",
                                "Erreur: pas une format propre pour un mail"),
                     "USA"=c("Add a profile picture",
                             "Write your surname",
                             "Write your first name",
                             "Enter your full address",
                             "Enter your email address",
                             "Enter your country code",
                             "Enter your telephone number",
                             "",
                             "Surname",
                             "First name",
                             "123 Charming Avenue, 02108 Boston MA, USA",
                             "Meriadoc.Brandybuck@Shire.com",
                             "+1",
                             "6177814567",
                             "Error, You must input a 10 digit number",
                             "Error, you must only use numbers",
                             "Error, not a proper format for an email address"),
                     row.names = c("photo",
                                   "nom",
                                   "prenom",
                                   "adresse",
                                   "mail",
                                   "countryCode",
                                   "numero",
                                   "photovalue",
                                   "nomValue",
                                   "prenomValue",
                                   "adresseValue",
                                   "mailValue",
                                   "countryCodeValue",
                                   "numeroValue",
                                   "phoneErreur",
                                   "chifreErreur",
                                   "mailErreur"))

usethis::use_data(paysdf, overwrite = TRUE)
